### PR TITLE
Dispatch start event only once when 2 or more triggers in mast file

### PR DESCRIPTION
**Pull request by ghost**
When there are several triggers in a mast file, the "start event" is dispatched for each trigger while the "end event" is dispatched when all triggers are processed.

### CODE REVIEW

**Comment by bbert** [comment]
Hi,
According to your modification, only pre-rolls triggers will send the 'start' event.
I think the 'start' event should be sent in the _activateTrigger() function.

**Comment by ghost** [comment]
Yes you 're right, the 'start' event is sent only in case of pre-rolls.
I sent it in _activateTrigger() function but add a test to send it only once.

**Comment by bbert** [comment]
I would prefer having a parameter when activating the trigger that indicates if the trigger is a first trigger of series, or if the trigger is activated consecutively to another.
I have submitted some modifications. Let me know if it works.

**Comment by ghost** [comment]
It is ok for me, checked on the sample.

**Pull request merged**
