### PR TITLE
Tracking event vast3 fix vast2

### PR DESCRIPTION
**Pull request by soledel**
add Vast3 tracking events : acceptInvitationLinear, exitFullscreen, progress, closeLinear
Fix vast2 tracking events : pause, rewind, Fullscreen

### CODE REVIEW

**Comment by bbert** [comment]
Hi,
Some general remarks:
- please do not include copyright at each line of code, it is unuseful. The license of the project is BCD-3. I have added CONTRIBUTORS.md file if you want to add your name to list of contributors.
- please make separate commits for each subject so that it can be easier to undertstand the modifications
- when you modify a line please remove the modified line instead of commenting it
- please align to used coding conventions, for example:

```
    if (....) {
    }
```
instead of 
```
    if (....)
    {
    }
```

Regarding 'pause' event handling:
- why do you listen event from MediaPlayer's element instead MediaPlayer itself? If the media is an image then it has not 'ended' attribute.
- I agree we should not consider 'paused' event raised at end of media playing. Maybe the pause event handling has to be modified by not listening for media 'paused' event but preferably listening for 'pause' action (when pause() method is called) ?

Regarding 'closeLinear' event:
- does MediaPlayer raise 'abort' event?
- looking at VAST3.0 specification, 'closeLinear' event should be raised when the user clicks on the close button. So we should thinking how integrating close (and skip) buttons and then manage the clicks on these buttons to raise the corresponding events. Another PR would be more appropriate.

**Comment by soledel** [comment]
I made changes regarding your general remarks.

Regarding  'closeLinear' event : I agree there is no 'abort' event. I had already fix this point the previous commit called 'fix closeLinear tracking event'. Taking into account the VAST3.0 specification $2.3.2.2 "The close event should only be trigerred if the user takes action to close the player or the window".

Regarding 'pause' event handling: 
I use MediaPlayer's video element because MediaPlayer's itself has no ended attribute. I thougth that pause and resume event wasn't used for image. I can not acces to navigation bar when the ad is an image.

**Comment by bbert** [comment]
Hi,
I have made some changes:
- added isEnded() function to media players
- mutualised fullscreen end exitFullscreen tracking events handlers

Last question regarding 'rewind' tracking event handler: what do you need to check if media element not null?

**Comment by soledel** [comment]
I notice that 'rewind' tracking event can be send randomly at the end of an ad.
I check that media element is not null in order to avoid to received extra rewind event add end of ad (When media element is not null, the getCurrentTime() function return 0 ) 
I guess that it can now be replace by (this._adMediaPlayer.isEnded() === false)

**Comment by bbert** [comment]
Hi,
You mean that 'timeupdate' event can be raised after 'ended' event?
I have never noticed that but no problem no control it, that makes sense.
I let you modify.

**Pull request merged**
